export enum DataType {
  STANDARD_OFFICE_DOCUMENTS = 'STANDARD_OFFICE_DOCUMENTS',
  NETWORKBASED_DATA = 'NETWORKBASED_DATA',
  DATABASES = 'DATABASES',
  IMAGES = 'IMAGES',
  STRUCTURED_GRAPHICS = 'STRUCTURED_GRAPHICS',
  AUDIOVISUAL_DATA = 'AUDIOVISUAL_DATA',
  SCIENTIFIC_STATISTICAL_DATA = 'SCIENTIFIC_STATISTICAL_DATA',
  RAW_DATA = 'RAW_DATA',
  PLAIN_TEXT = 'PLAIN_TEXT',
  STRUCTURED_TEXT = 'STRUCTURED_TEXT',
  ARCHIVED_DATA = 'ARCHIVED_DATA',
  SOFTWARE_APPLICATIONS = 'SOFTWARE_APPLICATIONS',
  SOURCE_CODE = 'SOURCE_CODE',
  CONFIGURATION_DATA = 'CONFIGURATION_DATA',
  OTHER = 'OTHER'
}
