import {Project} from './project';
import {Contributor} from './contributor';
import {Person} from './person';
import {DataKind} from './enum/data-kind.enum';
import {Dataset} from './dataset';
import {Host} from './host';
import {Cost} from './cost';
import {Storage} from './storage';

export interface Dmp {
  readonly created?: Date;
  readonly modified?: Date;
  readonly id: number;
  title?: string;
  description?: string;
  project: Project;
  contact: Person;
  contributors: Contributor[];
  dataKind: DataKind;
  noDataExplanation: string;
  datasets: Dataset[];
  metadata: string;
  dataGeneration: string;
  structure: string;
  targetAudience: string;
  tools: string;
  restrictedDataAccess: string;
  personalInformation: boolean;
  sensitiveData: boolean;
  sensitiveDataSecurity: string;
  legalRestrictions: boolean;
  ethicalIssuesExist: boolean;
  committeeApproved: boolean;
  ethicsReport: string;
  ethicalComplianceStatement: string;
  storage: Storage[];
  externalStorage: Storage[];
  externalStorageInfo: string;
  hosts: Host[];
  restrictedAccessInfo: string;
  closedAccessInfo: string;
  costsExist: boolean;
  costs: Cost[];
}
