import { Contributor } from './contributor';
import { Cost } from './cost';
import { DataKind } from './enum/data-kind.enum';
import { DataQualityType } from './enum/data-quality-type.enum';
import { Dataset } from './dataset';
import { ExternalStorage } from './external-storage';
import { Project } from './project';
import { Repository } from './repository';
import { Storage } from './storage';

export interface Dmp {
  readonly created?: Date;
  readonly modified?: Date;
  readonly id: number | null;
  title?: string;
  description?: string;
  project?: Project | null;
  contributors: Contributor[];
  dataKind: DataKind | null;
  reusedDataKind: DataKind | null;
  noDataExplanation: string;
  datasets: Dataset[];
  metadata: string;
  dataGeneration: string;
  documentation: string;
  dataQuality: DataQualityType[];
  otherDataQuality: string;
  structure: string;
  targetAudience: string;
  tools: string;
  restrictedDataAccess: string;
  personalData: boolean;
  personalDataCris: boolean | undefined;
  personalDataCompliance: string[];
  otherPersonalDataCompliance: string;
  sensitiveData: boolean;
  sensitiveDataCris: boolean | undefined;
  sensitiveDataSecurity: string[];
  otherDataSecurityMeasures: string;
  sensitiveDataAccess: string;
  legalRestrictions: boolean;
  legalRestrictionsCris: boolean | undefined;
  legalRestrictionsDocuments: string[];
  otherLegalRestrictionsDocument: string;
  legalRestrictionsComment: string;
  dataRightsAndAccessControl: string;
  humanParticipants: boolean;
  humanParticipantsCris: boolean | undefined;
  ethicalIssuesExist: boolean;
  ethicalIssuesExistCris: boolean | undefined;
  committeeReviewed: boolean;
  committeeReviewedCris: boolean | undefined;
  ethicalIssuesReport: string;
  storage: Storage[];
  externalStorage: ExternalStorage[];
  externalStorageInfo: string;
  repositories: Repository[];
  restrictedAccessInfo: string;
  closedAccessInfo: string;
  costsExist: boolean | null;
  costsExistCris: boolean | undefined;
  costs: Cost[];
}
