import {Dmp} from '../domain/dmp';
import {ContributorRole} from '../domain/enum/contributor-role.enum';
import {IdentifierType} from '../domain/enum/person-id-type.enum';
import {CostType} from '../domain/enum/cost-type.enum';
import {DataKind} from '../domain/enum/data-kind.enum';
import {DataAccessType} from '../domain/enum/data-access-type.enum';
import {AccessRight} from '../domain/enum/access-right';
import {ComplianceType} from '../domain/enum/compliance-type.enum';

export const completeDmp: Dmp = {
  closedAccessInfo: 'closed access info',
  committeeApproved: true,
  contact: {
    firstName: 'Max', id: 77, lastName: 'Mustermann', mbox: 'm.mustermann@university.ac.at', universityId: '12345', personId: null,
    affiliation: 'TU Wien', affiliationId: {identifier: 'XXX', type: IdentifierType.ROR}
  },
  contributors: [
    {
      id: 84, person: {
        firstName: 'Max', id: 85, lastName: 'Mustermann', mbox: 'm.mustermann@university.ac.at', universityId: '12345', personId: null,
        affiliation: 'TU Wien', affiliationId: {identifier: 'XXX', type: IdentifierType.ROR}
      }, role: ContributorRole.Editor
    },
    {
      id: 98,
      person: {
        firstName: 'Anna',
        id: 99,
        lastName: 'Musterfrau',
        mbox: 'm.musterfrau@university.ac.at',
        personId: {
          identifier: '0000-0000-0000-xxxx',
          type: IdentifierType.ORCID
        },
        affiliation: 'TU Wien', affiliationId: {identifier: 'XXX', type: IdentifierType.ROR},
        universityId: '23456'
      },
      role: ContributorRole.ProjectManager
    }
  ],
  costs: [
    {
      currencyCode: 'EUR',
      customType: null,
      description: 'cost description',
      id: 103,
      title: 'New cost',
      type: CostType.database,
      value: 123
    }
  ],
  costsExist: true,
  dataGeneration: 'research data will be generated by conducting a survey',
  dataKind: DataKind.SPECIFY,
  datasets: [
    {
      comment: '',
      dataAccess: DataAccessType.closed,
      id: 82,
      license: 'https://creativecommons.org/publicdomain/zero/1.0/',
      personalData: true,
      sensitiveData: true,
      legalRestrictions: true,
      referenceHash: '39608knzrof6y',
      size: 0,
      startDate: null,
      title: 'Dataset 1',
      type: 'STANDARD_OFFICE_DOCUMENTS',
      selectedProjectMembersAccess: AccessRight.write,
      otherProjectMembersAccess: AccessRight.read,
      publicAccess: AccessRight.none,
      delete: false,
      dateOfDeletion: null,
      reasonForDeletion: ''
    },
    {
      comment: '',
      dataAccess: DataAccessType.restricted,
      id: 83,
      license: 'https://creativecommons.org/publicdomain/zero/1.0/',
      personalData: true,
      sensitiveData: true,
      legalRestrictions: true,
      referenceHash: '39608knzrof6y',
      size: 0,
      startDate: null,
      title: 'Dataset 1',
      type: 'STANDARD_OFFICE_DOCUMENTS',
      selectedProjectMembersAccess: AccessRight.write,
      otherProjectMembersAccess: AccessRight.read,
      publicAccess: AccessRight.none,
      delete: true,
      dateOfDeletion: new Date(20000),
      reasonForDeletion: 'reason1'
    }
  ],
  ethicalComplianceStatement: 'statement regarding ethical compliance',
  ethicalIssuesExist: true,
  ethicsReport: 'link.to.report',
  externalStorage: [
    // TODO
    /*{
      hostId: 'TU Files',
      backupFrequency: 'Wien',
      backupLocation: null,
      datasets: [
        '39608ko19edx5'
      ],
      id: null,
      storageLocation: null,
      title: 'OtherStorage',
      url: 'github.com'
    }*/
  ],
  externalStorageInfo: 'because',
  hosts: [
    {
      datasets: [
        '39608knzrof6y'
      ],
      date: new Date(),
      hostId: 'r3d100013557',
      id: 94,
      title: 'TU Data'
    },
  ],
  id: 76,
  legalRestrictions: true,
  legalRestrictionsComment: 'legally restricted',
  metadata: 'provided metadata',
  noDataExplanation: '',
  personalData: true,
  personalDataAccess: 'only people with access can access',
  personalDataCompliance: ['item1', 'item2', ComplianceType.Other],
  otherPersonalDataCompliance: 'other measures',
  project: {
    end: new Date(),
    funding: {
      funderId: {
        identifier: '501100004955', type: IdentifierType.FUNDREF
      }, fundingStatus: 'GRANTED',
      grantId: {
        identifier: '123456',
        type: null
      }, id: 79
    },
    id: 78,
    start: new Date(),
    title: 'Project title',
    universityId: 1234,
    description: '',
    dmpExists: false
  },
  restrictedAccessInfo: 'info how someone can access restricted data',
  restrictedDataAccess: 'send form',
  sensitiveData: true,
  sensitiveDataSecurity: 'data will be stored in a vault',
  storage: [
    {
      datasets: [
        '39608knzrof6y'
      ],
      hostId: '0',
      id: 97,
      title: 'TUfiles',
      // url: 'it.tuwien.ac.at'
    }
  ],
  structure: 'VCS',
  targetAudience: 'students',
  tools: 'proprietary software needed'
};

export const noDataDmp: Dmp = {
  closedAccessInfo: 'closed access info',
  committeeApproved: true,
  contact: {
    firstName: 'Max', id: 77, lastName: 'Mustermann', mbox: 'm.mustermann@university.ac.at', universityId: '12345', personId: null,
    affiliation: 'TU Wien', affiliationId: {identifier: 'XXX', type: IdentifierType.ROR}
  },
  contributors: [
    {
      id: 84, person: {
        firstName: 'Max', id: 85, lastName: 'Mustermann', mbox: 'm.mustermann@university.ac.at', universityId: '12345', personId: null,
        affiliation: 'TU Wien', affiliationId: {identifier: 'XXX', type: IdentifierType.ROR}
      }, role: ContributorRole.Editor
    },
    {
      id: 98,
      person: {
        firstName: 'Anna',
        id: 99,
        lastName: 'Musterfrau',
        mbox: 'm.musterfrau@university.ac.at',
        personId: {
          identifier: '0000-0000-0000-xxxx',
          type: IdentifierType.ORCID
        },
        affiliation: 'TU Wien', affiliationId: {identifier: 'XXX', type: IdentifierType.ROR},
        universityId: '23456'
      },
      role: ContributorRole.ProjectManager
    }
  ],
  costs: [
    {
      currencyCode: 'EUR',
      customType: null,
      description: 'cost description',
      id: 103,
      title: 'New cost',
      type: CostType.database,
      value: 123
    }
  ],
  costsExist: true,
  dataGeneration: 'research data will be generated by conducting a survey',
  dataKind: DataKind.NONE,
  datasets: [
    {
      comment: '',
      dataAccess: DataAccessType.closed,
      id: 82,
      license: 'https://creativecommons.org/publicdomain/zero/1.0/',
      personalData: true,
      sensitiveData: true,
      legalRestrictions: true,
      referenceHash: '39608knzrof6y',
      size: 0,
      startDate: null,
      title: 'Dataset 1',
      type: 'STANDARD_OFFICE_DOCUMENTS',
      selectedProjectMembersAccess: AccessRight.write,
      otherProjectMembersAccess: AccessRight.read,
      publicAccess: AccessRight.none,
      delete: false,
      dateOfDeletion: new Date(20000),
      reasonForDeletion: 'reason2'
    },
    {
      comment: '',
      dataAccess: DataAccessType.restricted,
      id: 83,
      license: 'https://creativecommons.org/publicdomain/zero/1.0/',
      personalData: true,
      sensitiveData: true,
      legalRestrictions: true,
      referenceHash: '39608knzrof6y',
      size: 0,
      startDate: null,
      title: 'Dataset 1',
      type: 'STANDARD_OFFICE_DOCUMENTS',
      selectedProjectMembersAccess: AccessRight.write,
      otherProjectMembersAccess: AccessRight.read,
      publicAccess: AccessRight.none,
      delete: true,
      dateOfDeletion: new Date(20000),
      reasonForDeletion: 'reason1'
    }
  ],
  ethicalComplianceStatement: 'statement regarding ethical compliance',
  ethicalIssuesExist: false,
  ethicsReport: 'link.to.report',
  externalStorage: [
    {
      hostId: 'TU Files',
      backupFrequency: 'Wien',
      backupLocation: null,
      datasets: [
        '39608ko19edx5'
      ],
      id: null,
      storageLocation: null,
      title: 'OtherStorage',
      url: 'github.com'
    }
  ],
  externalStorageInfo: 'because',
  hosts: [
    {
      datasets: [
        '39608knzrof6y'
      ],
      date: new Date(),
      hostId: 'r3d100013557',
      id: 94,
      title: 'TU Data'
    },
  ],
  id: 76,
  legalRestrictions: true,
  legalRestrictionsComment: 'legally restricted',
  metadata: 'provided metadata',
  noDataExplanation: '',
  personalData: true,
  personalDataAccess: 'only people with access can access',
  personalDataCompliance: ['item1', 'item2'],
  otherPersonalDataCompliance: 'other measures',
  project: {
    end: new Date(),
    funding: {
      funderId: {
        identifier: '501100004955', type: IdentifierType.FUNDREF
      }, fundingStatus: 'GRANTED',
      grantId: {
        identifier: '123456',
        type: null
      }, id: 79
    },
    id: 78,
    start: new Date(),
    title: 'Project title',
    universityId: 1234,
    description: '',
    dmpExists: false
  },
  restrictedAccessInfo: 'info how someone can access restricted data',
  restrictedDataAccess: 'send form',
  sensitiveData: true,
  sensitiveDataSecurity: 'data will be stored in a vault',
  storage: [
    {
      datasets: [
        '39608knzrof6y'
      ],
      hostId: '0',
      id: 97,
      title: 'TUfiles',
      // url: 'it.tuwien.ac.at'
    }
  ],
  structure: 'VCS',
  targetAudience: 'students',
  tools: 'proprietary software needed'
};
