export enum Agreement {
  CONSORTIUM_AGREEMENT = 'CONSORTIUM_AGREEMENT',
  DATA_PROCESSING_AGREEMENT = 'DATA_PROCESSING_AGREEMENT',
  JOINT_CONTROL_AGREEMENT = 'JOINT_CONTROL_AGREEMENT',
  CONFIDENTIALITY_AGREEMENT = 'CONFIDENTIALITY_AGREEMENT',
  OTHER = 'OTHER'
}
