export enum ContributorRole {
  DATA_COLLECTOR = 'Data Collector',
  DATA_CURATOR = 'Data Curator',
  DATA_MANAGER = 'Data Manager',
  DISTRIBUTOR = 'Distributor',
  EDITOR = 'Editor',
  HOSTING_INSTITUTION = 'Hosting Institution',
  PRODUCER = 'Producer',
  PROJECT_LEADER = 'Project Leader',
  PROJECT_MANAGER = 'Project Manager',
  PROJECT_MEMBER = 'Project Member',
  REGISTRATION_AGENCY = 'Registration Agency',
  REGISTRATION_AUTHORITY = 'Registration Authority',
  RELATED_PERSON = 'Related Person',
  RESEARCHER = 'Researcher',
  RESEARCH_GROUP = 'Research Group',
  RIGHTS_HOLDER = 'Rights Holder',
  SPONSOR = 'Sponsor',
  SUPERVISOR = 'Supervisor',
  WORK_PACKAGE_LEADER = 'Work Package Leader',
  OTHER = 'Other'
}
