export enum CostType {
  DATA_ACQUISITION = 'DATA_ACQUISITION',
  DATABASE = 'DATABASE',
  FILE_BASED_STORAGE = 'FILE_BASED_STORAGE',
  HARDWARE_AND_INFRASTRUCTURE = 'HARDWARE_AND_INFRASTRUCTURE',
  LEGAL_ADVICE = 'LEGAL_ADVICE',
  PERSONNEL = 'PERSONNEL',
  REPOSITORY = 'REPOSITORY',
  SOFTWARE_LICENSE = 'SOFTWARE_LICENSE',
  TRAINING = 'TRAINING',
  OTHER = 'OTHER'
}
