export enum DataQualityType {
  CALIBRATION = 'CALIBRATION',
  REPEATED_SAMPLES_OR_MEASUREMENTS = 'REPEATED_SAMPLES_OR_MEASUREMENTS',
  STANDARDISED_DATA_CAPTURE = 'STANDARDISED_DATA_CAPTURE',
  DATA_ENTRY_VALIDATION = 'DATA_ENTRY_VALIDATION',
  PEER_REVIEW_OF_DATA = 'PEER_REVIEW_OF_DATA',
  REPRESENTATION_WITH_CONTROLLED_VOCABULARIES = 'REPRESENTATION_WITH_CONTROLLED_VOCABULARIES',
  OTHERS = 'OTHERS'
}
