export enum SecurityMeasure {
  INDIVIDUAL_LOGIN = 'INDIVIDUAL_LOGIN',
  ADDITIONAL_LOGIN = 'ADDITIONAL_LOGIN',
  AUTOMATIC_LOCKING_OF_CLIENTS = 'AUTOMATIC_LOCKING_OF_CLIENTS',
  ENCRYPTION_OF_SYSTEMS = 'ENCRYPTION_OF_SYSTEMS',
  LOCKED_STORAGE = 'LOCKED_STORAGE',
  OTHER = 'OTHER'
}
